"""empty message

Revision ID: 530e0b382e61
Revises: 4bc8676d64be
Create Date: 2022-06-05 14:08:42.220609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530e0b382e61'
down_revision = '4bc8676d64be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
